language: cpp

branches:
  only:
    # - master
    # Build all branches
    - /.*/

git:
  # Need full depth for git describe (see package_linux.sh)
  depth: false

env:
  global:
    - DEPS_DIR=${HOME}/deps
    - secure: "GdizAkQ9Biz59hnmruV5jm8zpLrY/2BKY6q6+3jbStgvNeiWFAqlvpDirqj+rfCOwSvDQ3cPPwW8H2+IAvqZQoFdRElzwkDO0rI/qAgUgY6bTvrxWgayJAmHjWgUkr1uWsohDlo+CL5GsCFX8lJ2IfQm+/gNP+ayLZ17nZv9W2cwCRBMcw5c8ULHcE9razTa1lAxQhS4hgOGBs2iJV+CIaNzO7stcdQ6C/WQbhd77Raxy1xBaEuCc/cv1sjSm8IUrdLd5HiMEN4pjUhFVOkAQFMPdnqoFhLLMncYMCoOrck6cjIjJ1o+im1Zmb/EZjzOFXXS0f62adxVwIOyWBElhmjINy511+it2OFWV2lzL3SgFNSgw9lwNMtEDvYkTHmmWAyJlCsNnsqvZorjXd1vxgAt5dD5AXh2GQlfI6m3xP60PgPN7Y2EPT0CTgwakPfKNByQCyWW8SxKGYLbH54dR8leLCwI2ni5aTBTgtVGzwl5wQUGiXXym+GuOddRm2D89yhvgLqxNG3UnvRygQy7BwjAF/QEaqGNKgNmkC/luGqVncNVfz7IKOnivbeUKLgaz8c2qtKVbETiQKJg4fO7I8l9pp9w4SvCnAZyh42fPJxsEgol+/RjJdsDpFsd/WZLOnt0i8j70vE0/N1kVFaX4EYMkbU1IxX8VcnRRa4zjrw="
    - secure: "BQPHdwAu3W04GHyBXdRwTyzUpQIlOUySWkAV2Ovklo76T8j0e2kagTO8jAQ9/s/79C1SrdWDOEwOSS1vmXd1dSa2ktWddJY0F4YO/suVE9ljNQpbcxQLzokXUfSmVdTWk3F/t+8NdSXTojV2qYj92OhmeXajMXzWS4xDSK8679ymXb3HY0lvOXHae16tKg6oGwVafEqi0Ec+YOUs6KhRe8yYGZ//F+bxtxq4Do/Kgz/HYlThXD0QRku+4iDrSRDmoUKAT2ZfHB/gUdPSPXu4urMGEV0yUjoMU7GeNaxOKQ2vDW+U9vHJaGaXb43xU4fPLTlyXfpS2UKMbuOIexbU10fz5A5gcLREy6SDzgpDlu/erfMz7xdJNtLbouPl9RwOhF9+2A1WRrLsyAownRhsLxoe+zphmYO2DGPTIRKKjCROOi1FMrA53WEr5Djx3H8LTL9KjHH3Dv3a3wCj1BRA5xDbs0PGMQZSyzts946NoaW7XMbQKVct/T4c49oU47RBGsYfrTxyqJZaRQBGdIZWOZ0Bu3bmluTewH9rI/zWmawYIo/rceaVvF8lQHqfLV0vfFlPzhuxepGjU7bJ+KuvQqBJI3MssBydn9zPg3IXZwMTMxEzdPA06YlBAL83TYkuOJx6MrkfqsrYc3rHZZbhl1b9JV47oj6fehl4LxaT3tI="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      group: deprecated-2017Q4
      compiler: gcc-8
      env:
        - VCPKG_TRIPLET=x64-linux
        - CC_COMPILER=gcc-8
        - CXX_COMPILER=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libgtk2.0-dev
            - lftp
            # SDL build dependencies
            # See: https://hg.libsdl.org/SDL/file/default/docs/README-linux.md
            - libtool
            - libasound2-dev
            - libpulse-dev
            - libaudio-dev
            - libx11-dev
            - libxext-dev
            - libxrandr-dev
            - libxcursor-dev
            - libxi-dev
            - libxinerama-dev
            - libxxf86vm-dev
            - libxss-dev
            - libgl1-mesa-dev
            - libesd0-dev
            - libdbus-1-dev
            - libudev-dev
            - libgles1-mesa-dev
            - libgles2-mesa-dev
            - libegl1-mesa-dev
            - libibus-1.0-dev
            - fcitx-libs-dev
            - libsamplerate0-dev
            - libsndio-dev

before_install:
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}
  - # Get a more recent version of CMake
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - export CMAKE_INSTALL_SCRIPT=cmake-3.14.0-Linux-x86_64.sh
  - wget https://github.com/Kitware/CMake/releases/download/v3.14.0/${CMAKE_INSTALL_SCRIPT}
  - chmod +x ${CMAKE_INSTALL_SCRIPT}
  - ./${CMAKE_INSTALL_SCRIPT} --prefix=$HOME/usr --exclude-subdir --skip-license

install:
  # HACK: gcc 8.0.1 is missing movdirintrin.h so just download it. We need this for GLM and Vectrexy to build.
  - sudo wget https://raw.githubusercontent.com/gcc-mirror/gcc/gcc-8-branch/gcc/config/i386/movdirintrin.h -P /usr/lib/gcc/x86_64-linux-gnu/8/include/

  # Create deps dir
  - mkdir -p ${DEPS_DIR}

  # Set compiler vars
  - export CC=${CC_COMPILER}
  - export CXX=${CXX_COMPILER}

  # Install vcpkg and dependencies
  - |
    set -e
    mkdir -p ${DEPS_DIR}/vcpkg
    pushd ${DEPS_DIR}/vcpkg
    git init
    git remote add origin https://github.com/Microsoft/vcpkg.git
    git fetch origin master
    git checkout -b master origin/master
    ./bootstrap-vcpkg.sh
    # Only build release libs to save time. We inject a new line first since some cmake files don't end with one.
    echo -e '\nset(VCPKG_BUILD_TYPE release)' >> ./triplets/${VCPKG_TRIPLET}.cmake
    ./vcpkg install sdl2 sdl2-net glew glm stb imgui
    popd

cache:
  directories:
    - ${DEPS_DIR}/vcpkg/installed

script:
  - |
    set -e
    # Package and deploy only on master branch
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      mkdir -p build && cd build
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_TOOLCHAIN_FILE=${DEPS_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake ..
      make -j
      cd ..
      bash ./tools/package/package_linux.sh vectrexy_linux64 https://dl.bintray.com/amaiorano/vectrexy/
    fi

deploy:
  on: master
  #on:
  #  all_branches: true
  provider: bintray
  file: ./tools/package/travis_bintray_descriptor.json
  user: amaiorano
  key:
    secure: tHxPYNa/mqXd47nK0FEnx7s9O1mQYRUohjSyTn3WmfsThpxAx8NmNGCj26vs9noLXnPeXEWtDg2vEc28OH37dKLAdGEmEWX7XRgrSOhmbh1kIYjPSNO82SPGgk7yk2L6kv38RD/pvA/mF8piWmRTLgkxYPaoQGmxVPtO/h2krRxebipu+A0XhAbwIgS9Zwd4kpXHAsSaduQuKZLTCqGZnSmfMyjzG6cn6rDZTDOggotmxZQBd0bBemDB5ZXqKFI9AP1WxvTulAS7JMtsJvZIRK00vZGQyA9aUErliD4EXbZYzeY+fVToHe2nBvH1EimYEzsySPuwGQTg6jL+wrHqym2gCyHMtjXPjGZwAvm0zbtqahb40f+g2p1PCg80q5YwdpYclMdmrO3c9wjcU+/D9KZoLo4+g00QhzF5/xOme45uuLgApndbj0tZCosGYCBMAPWo56WwIi4W1iXik9B0wnCHgoLDGXc5rtHy4VZmgKnr/YBkZ3d9gPm1CWCWVBriacq8p0EdAYoQZIEN8JXrB+SUuVm1eQyresG8xj/DLMT13APYJWyykq/kGeksDg1vrE+2YLYN0o5DeF7btv7WPRk2jTGyeqMDWkBDU7pjg+lbbhfv25Ra8diSUbDXLuPhNuMWU/exOeHXvlntN0Wk2GCWa9TojfFKZMNbcTyJeCQ=
  skip_cleanup: true
