version: '{branch}-{build}'
image: Visual Studio 2017
configuration: RelWithDebInfo
platform: x64
clone_folder: C:\projects\vectrexy\

init:
- cmd: 

clone_script:
- cmd: >-
    git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    
    git checkout -qf %APPVEYOR_REPO_COMMIT%

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

install:
- cmd: >-
    echo Installing dependencies
    
    cd /d c:\projects
    
    git clone https://github.com/Microsoft/vcpkg
    
    cd vcpkg
    
    .\bootstrap-vcpkg.bat
    
    echo.set(VCPKG_BUILD_TYPE release)>> c:\projects\vcpkg\triplets\x64-windows-static.cmake
    
    vcpkg install sdl2:x64-windows-static sdl2-net:x64-windows-static glew:x64-windows-static glm:x64-windows-static stb:x64-windows-static imgui:x64-windows-static

    
    echo Generating vectrexy sln
    
    cd /d c:\projects\vectrexy
    
    mkdir build && cd build
    
    cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=C:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static ..
    
    cd ..

build:
  project: C:\projects\vectrexy\
  parallel: true
  verbosity: minimal

after_build:
- cmd: >-
    .\package\package_windows.bat vectrexy_win64 https://daroou.000webhostapp.com/vectrexy/package/

artifacts:
- path: vectrexy_win64/
  name: vectrexy_win64

notifications:
- provider: Email
  to:
  - amaiorano@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

deploy: off

for:

# Deploy only for master branch
-
  branches:
    only:
    - master
  deploy:
    provider: FTP
    host: files.000webhost.com
    protocol: ftp
    username: daroou
    password:
      secure: KoprVjPZkpO98R+JgKuAaZUXHrUVBwY6kPwdvaMTuqk=
    folder: public_html/vectrexy/build
    active_mode: false
    beta: true
    debug: true
